server:
  port: ${SERVER_PORT:32221}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/secret_archive
    username: postgres
    password: password
    defaultAutoCommit: false
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    open-in-view: false
